[prometheus]
testbox ansible_host=ip.add.re.ss ansible_user=debian ansible_ssh_private_key_file=/home/debian/.ssh/google_compute_engine ansible_ssh_common_args='-o CheckHostIP=no -o HashKnownHosts=no -o HostKeyAlias=compute.redacted -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/home/debian/.ssh/google_compute_known_hosts'

# GCP note
# on GCP use (--dry-run) flag to get
# the necessary param values for the above  
# gcloud compute ssh boxname --zone=$ZONE --dry-run

# laptop's test virsh
# [prometheus]
# 192.168.122.183 ansible_user=ansible ansible_ssh_private_key_file=/home/paco/.ssh/ansible_deployment_id_rsa