[program:prometheus]
command=/opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml --storage.tsdb.path="/data/prometheus"
user=prometheus
stdout_logfile=/var/log/prometheus/prometheus.log
redirect_stderr=true
